# Generated by Django 2.2 on 2019-04-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeragetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('sales_team', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('sendemail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerdetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('website', models.CharField(max_length=255)),
                ('vat_number', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='customer_details_image')),
            ],
        ),
        migrations.CreateModel(
            name='groupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_data', models.CharField(max_length=255)),
                ('customer_details', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerdetailsModel')),
            ],
        ),
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_billing', models.CharField(max_length=255)),
                ('city_billing', models.CharField(max_length=255)),
                ('state_billing', models.CharField(max_length=255)),
                ('zip_code_billing', models.CharField(max_length=255)),
                ('country_billing', models.CharField(max_length=255)),
                ('customer_details', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerdetailsModel')),
            ],
        ),
    ]
