# Generated by Django 2.2 on 2019-04-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeragetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('sales_team', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('sendemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
