# Generated by Django 2.2 on 2019-04-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
    ]
