# Generated by Django 2.2 on 2019-04-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcategorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorymodel',
            old_name='category_status',
            new_name='sub_category_status',
        ),
    ]
