# Generated by Django 2.2 on 2019-04-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190411_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorymodel',
            old_name='category_description',
            new_name='sub_category_description',
        ),
    ]
