# Generated by Django 2.2 on 2019-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_itemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/'),
        ),
    ]
