# Generated by Django 2.2 on 2019-04-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_itemmodel_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_image',
            field=models.FileField(default='pic_folder/None/no-img.jpg', upload_to='images/'),
        ),
    ]
