# Generated by Django 2.2 on 2019-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190413_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/'),
        ),
    ]
