# Generated by Django 2.2 on 2019-04-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190413_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
