# Generated by Django 2.2 on 2019-04-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190413_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('sales_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
